# Docker Compose for TheCaptain989's MovieGnomes
#  https://github.com/TheCaptain989/moviegnomes

version: '3'
name: moviegnomes
services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment: &default-env
      - PUID=1009
      - PGID=1000
      - TZ=America/Chicago
    volumes: &default-vols
      - ${CONFIG_ROOT_PATH:?err}:/config
      - media:/media
    ports:
      - 8080:8080/tcp
    tty:
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    profiles:
      - movie
    depends_on:
      - sabnzbd
    environment:
      << : *default-env
      - PUID=1010
      - DOCKER_MODS="linuxserver/mods:radarr-striptracks"
    volumes: *default-vols
    ports:
      - 7878:7878/tcp
    tty:
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    profiles:
      - tv
    depends_on:
      - sabnzbd
    environment:
      << : *default-env
      - PUID=1011
      - DOCKER_MODS="linuxserver/mods:radarr-striptracks"
    volumes: *default-vols
    ports:
      - 8989:8989/tcp
    tty:
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    profiles:
      - movie
      - tv
    depends_on:
      - radarr
      - sonarr
    environment:
      << : *default-env
      - PUID=1012
    volumes: *default-vols
    ports:
      - 6767:6767/tcp
    tty:
    restart: unless-stopped

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    profiles:
      - music
    depends_on:
      - sabnzbd
    environment:
      << : *default-env
      - PUID=1013
      - DOCKER_MODS="linuxserver/mods:lidarr-flac2mp3"
    volumes: *default-vols
    ports:
      - 8686:8686/tcp
    tty:
    restart: unless-stopped

  kodi:
    image: matthuisman/kodi-headless:Matrix
    container_name: kodi
    profiles:
      - stream
    environment:
      << : *default-env
      - PUID=1014
    volumes:
      - ${CONFIG_ROOT_PATH:?err}:/config
    ports:
      - 8085:8080/tcp
    tty:
    restart: unless-stopped

volumes:
  media:
    external:
      name: ${MEDIA_ROOT_PATH:?err}
      
secrets:
  passwords:
    file: ./logins.xml
